name: ci-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: |
            georgebott/postgres_web3:latest
            georgebott/postgres_web3:alpine
            georgebott/postgres_web3:15-alpine
            georgebott/postgres_web3:15.2-alpine
            ghcr.io/Yen/postgres_web3:latest
            ghcr.io/Yen/postgres_web3:alpine
            ghcr.io/Yen/postgres_web3:15-alpine
            ghcr.io/Yen/postgres_web3:15.2-alpine
